echo "pond@prod:~$ whoami"
echo "pond_np31 (DevOps Engineer)"
echo ""
echo "pond@prod:~$ kubectl get nodes"
echo "prod-node-1   Ready"
echo "prod-node-2   Ready"
echo ""
echo "pond@prod:~$ docker ps"
echo "api-service        running"
echo "web-frontend       running"
echo "postgres-db        healthy"
echo ""
echo "pond@prod:~$ terraform plan"
echo "No changes. Infrastructure is up-to-date."
echo ""
echo "pond@prod:~$ uptime"
echo "production running since 2022 ☁️"
